services:
  - type: web
    name: plant-health-assistant
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PROCESS_ASYNC
        value: "true"
