export const config = {
  appName: process.env.NEXT_PUBLIC_APP_NAME ?? "Plant Health Assistant",
  baseUrl: process.env.APP_BASE_URL ?? "http://localhost:3000",
  adminApiKey: process.env.ADMIN_API_KEY ?? "dev-admin-key",
  provider: (process.env.WHATSAPP_PROVIDER ?? "meta") as "meta" | "twilio",
  verifyToken: process.env.WHATSAPP_VERIFY_TOKEN ?? "verify-token",
  whatsappPhoneNumberId: process.env.WHATSAPP_PHONE_NUMBER_ID ?? "",
  whatsappAccessToken: process.env.WHATSAPP_ACCESS_TOKEN ?? "",
  whatsappAppSecret: process.env.WHATSAPP_APP_SECRET ?? "",
  whatsappApiVersion: process.env.WHATSAPP_API_VERSION ?? "v22.0",
  databaseUrl: process.env.DATABASE_URL ?? "",
  supabaseUrl: process.env.NEXT_PUBLIC_SUPABASE_URL ?? "",
  supabaseServiceRoleKey: process.env.SUPABASE_SERVICE_ROLE_KEY ?? "",
  supabaseBucket: process.env.SUPABASE_STORAGE_BUCKET ?? "plant-images",
  aiProvider: process.env.AI_PROVIDER ?? "openai",
  aiApiKey: process.env.AI_API_KEY ?? "",
  aiVisionModel: process.env.AI_VISION_MODEL ?? "gpt-4.1-mini",
  aiTextModel: process.env.AI_TEXT_MODEL ?? "gpt-4.1-mini",
  plantModelProvider: process.env.PLANT_MODEL_PROVIDER ?? "none",
  plantModelApiKey: process.env.PLANT_MODEL_API_KEY ?? "",
  plantModelEndpoint: process.env.PLANT_MODEL_ENDPOINT ?? "https://api.plant.id/v3/health_assessment",
  plantModelProvider2: process.env.PLANT_MODEL_PROVIDER_2 ?? "none",
  plantModelApiKey2: process.env.PLANT_MODEL_API_KEY_2 ?? "",
  plantModelEndpoint2: process.env.PLANT_MODEL_ENDPOINT_2 ?? "",
  searchProvider: process.env.SEARCH_PROVIDER ?? "tavily",
  searchApiKey: process.env.SEARCH_API_KEY ?? "",
  rateLimitWindowMs: Number(process.env.RATE_LIMIT_WINDOW_MS ?? 60000),
  rateLimitMaxRequests: Number(process.env.RATE_LIMIT_MAX_REQUESTS ?? 20),
  queueSecret: process.env.QUEUE_SECRET ?? "queue-secret",
  processAsync: process.env.PROCESS_ASYNC === "true",
  queueMaxAttempts: Number(process.env.QUEUE_MAX_ATTEMPTS ?? 5),
  queueRetryBaseMs: Number(process.env.QUEUE_RETRY_BASE_MS ?? 30000),
  logLevel: process.env.LOG_LEVEL ?? "info",
  appEnv: process.env.NODE_ENV ?? "development"
};
